---
- name: Initial Server Hardening for Ubuntu
  hosts: all
  vars:
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Allow SSH before enabling UFW
      ansible.builtin.ufw:
        rule: allow
        name: OpenSSH

    - name: Add SSH key for AWX
      ansible.builtin.authorized_key:
        user: ubuntu
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINQN0xMG31YYdl4ErPfelk7qI5Xd2WqjHiH6vf5CeC6f awx_gitlab"


    - name: Enable UFW
      ansible.builtin.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Ensure system is using the latest CA certificates
      ansible.builtin.apt:
        name: ca-certificates
        state: latest

    - name: Ensure systemd-timesyncd service is stopped
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: stopped

    - name: Install Chrony
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Remove default NTP servers
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: "^server "
        line: "# Commented out by Ansible"
        state: absent

    - name: Add specified NTP servers to chrony.conf
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "server {{ item }} iburst"
        insertafter: EOF
      loop: "{{ ntp_servers }}"
      notify: restart chrony

    - name: Ensure Chrony is enabled and running
      ansible.builtin.service:
        name: chrony
        state: started
        enabled: yes
    - name: Allow user to execute sudo commands without a password
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/your_username"
        content: "your_username ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'
        owner: root
        group: root
        mode: '0440'
      become: yes


  handlers:
    - name: restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted
